# Site
title: Cinthia Mendonça

# URL
url: http://cinthia.mobi
baseurl: '/cinthia.mobi'
permalink: :title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 4664

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      cover: "/assets/covers/homecover.jpg"

# Data
social:
  facebook_url: "https://www.facebook.com/CinthiaMendonca"
  twitter_url: "https://twitter.com/haikaio"
  twitter_user: "@haikaio"
